name: pivx-core
base: core18
version: 5.0.1
summary:   peer-to-peer network based digital currency
description: |
  PIVX is an MIT licensed,
  open source, blockchain-based cryptocurrency with
  ultra fast transactions, low fees, high network decentralization, and
  Zero Knowledge cryptography proofs for industry-leading
  transaction anonymity.

  - [Download](https://pivx.org/wp-content/uploads/2018/10/PIVX-White.pdf) PIVX White Paper PDF
grade: stable
confinement: strict

apps:
  daemon:
    command: pivxd
    plugs: [network, network-bind, removable-media]
    environment:
      # Override HOME so the pivx datadir is located at
      # ~/snap/pivx/common/.pivx instead of
      # ~/snap/pivx/current/.pivx, and each new version of the pivx
      # snap won't have a different data directory:
      # https://docs.snapcraft.io/environment-variables/7983
      HOME: $SNAP_USER_COMMON
  qt:
    command: desktop-launch pivx-qt
    plugs: [network, network-bind, unity7, desktop, desktop-legacy, wayland, x11, mir, opengl, gsettings, removable-media, screen-inhibit-control, pulseaudio, media-hub]
    environment:
      HOME: $SNAP_USER_COMMON
  cli:
    command: pivx-cli
    plugs: [network, removable-media]
    environment:
      HOME: $SNAP_USER_COMMON

layout:
  /usr/share/pivx/sapling-spend.params:
    bind-file: $SNAP/share/pivx/sapling-spend.params
  /usr/share/pivx/sapling-output.params:
    bind-file: $SNAP/share/pivx/sapling-output.params

parts:

  # Remote part for support of various desktop technologies
  # Refer: https://github.com/ubuntu/snapcraft-desktop-helpers/blob/master/snapcraft.yaml
  desktop-qt5:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-depth: 1
    source-subdir: qt

    plugin: make
    make-parameters: [ "FLAVOR=qt5" ]
    build-packages:
      - build-essential
      - qtbase5-dev
      - dpkg-dev
    stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libqt5gui5
      - libgdk-pixbuf2.0-0
      - libqt5svg5 # for loading icon themes which are svg
      - try: [ appmenu-qt5 ] # not available on core18
      - locales-all
      - xdg-user-dirs
      - fcitx-frontend-qt5

  pivx-core:
    plugin: nil
    override-build: |
      env | grep SNAP
      wget https://github.com/PIVX-Project/PIVX/releases/download/v${SNAPCRAFT_PROJECT_VERSION}/SHA256SUMS.asc
      wget https://github.com/PIVX-Project/PIVX/releases/download/v${SNAPCRAFT_PROJECT_VERSION}/pivx-${SNAPCRAFT_PROJECT_VERSION}.tar.gz
      if [ $SNAPCRAFT_ARCH_TRIPLET = "i386-linux-gnu" ]
      then
        wget https://github.com/PIVX-Project/PIVX/releases/download/v${SNAPCRAFT_PROJECT_VERSION}/pivx-${SNAPCRAFT_PROJECT_VERSION}-i686-pc-linux-gnu.tar.gz
      else
        wget https://github.com/PIVX-Project/PIVX/releases/download/v${SNAPCRAFT_PROJECT_VERSION}/pivx-${SNAPCRAFT_PROJECT_VERSION}-${SNAPCRAFT_ARCH_TRIPLET}.tar.gz
      fi
      gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 6F993B250557E7B016ADE5713BDCDA2D87A881D9
      gpg --verify SHA256SUMS.asc
      sha256sum --ignore-missing --check SHA256SUMS.asc
      if [ $SNAPCRAFT_ARCH_TRIPLET = "i386-linux-gnu" ]
      then
        tar -xvf pivx-${SNAPCRAFT_PROJECT_VERSION}-i686-pc-linux-gnu.tar.gz
      else
        tar -xvf pivx-${SNAPCRAFT_PROJECT_VERSION}-${SNAPCRAFT_ARCH_TRIPLET}.tar.gz
      fi
      tar -xvf pivx-${SNAPCRAFT_PROJECT_VERSION}.tar.gz
      install -m 0644 -D -t $SNAPCRAFT_PART_INSTALL/share/pivx pivx-${SNAPCRAFT_PROJECT_VERSION}/share/pivx/sapling-spend.params
      install -m 0644 -D -t $SNAPCRAFT_PART_INSTALL/share/pivx pivx-${SNAPCRAFT_PROJECT_VERSION}/share/pivx/sapling-output.params
      install -m 0644 -D -t /usr/share/pivx pivx-${SNAPCRAFT_PROJECT_VERSION}/share/pivx/sapling-spend.params
      install -m 0644 -D -t /usr/share/pivx pivx-${SNAPCRAFT_PROJECT_VERSION}/share/pivx/sapling-output.params
      echo "Running tests ..."
      pivx-${SNAPCRAFT_PROJECT_VERSION}/bin/test_pivx
      install -m 0755 -D -t $SNAPCRAFT_PART_INSTALL/bin pivx-${SNAPCRAFT_PROJECT_VERSION}/bin/pivxd
      install -m 0755 -D -t $SNAPCRAFT_PART_INSTALL/bin pivx-${SNAPCRAFT_PROJECT_VERSION}/bin/pivx-qt
      install -m 0755 -D -t $SNAPCRAFT_PART_INSTALL/bin pivx-${SNAPCRAFT_PROJECT_VERSION}/bin/pivx-cli
      wget https://raw.githubusercontent.com/pivx-project/pivx/v${SNAPCRAFT_PROJECT_VERSION}/share/pixmaps/pivx128.png
      install -m 0644 -D -t $SNAPCRAFT_PART_INSTALL/share/pixmaps pivx128.png
    build-packages:
      - wget
      - dirmngr
    after:
      - desktop-qt5
